param(
  [Parameter(ValueFromRemainingArguments = $true)]
  [string[]]$FlutterArgs
)

$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$localAppData = Join-Path $repoRoot '.dart_appdata'
New-Item -ItemType Directory -Force -Path $localAppData | Out-Null
$env:APPDATA = $localAppData

if ($FlutterArgs.Count -eq 0) {
  $FlutterArgs = @('test')
} elseif ($FlutterArgs[0] -ne 'test') {
  $FlutterArgs = @('test') + $FlutterArgs
}

$flutterBin = $env:FLUTTER_BIN
if ([string]::IsNullOrWhiteSpace($flutterBin)) {
  $defaultFlutter = 'F:\FlutterSDK\flutter\bin\flutter.bat'
  $flutterBin = if (Test-Path $defaultFlutter) { $defaultFlutter } else { 'flutter' }
}

$overridePath = Join-Path $repoRoot 'pubspec_overrides.yaml'
$createdOverride = $false
$isWindowsHost = ($PSVersionTable.PSEdition -eq 'Desktop') -or ($IsWindows -eq $true)
$exitCode = 0
$generatedOverrideHeader = '# Generated by tool/flutter_test.ps1 for local Windows tests.'
$generatedOverride = @"
$generatedOverrideHeader
hooks:
  user_defines:
    sqlite3:
      source: system
      name_windows: winsqlite3
      name: sqlite3
"@

try {
  if ($isWindowsHost -and (Test-Path $overridePath)) {
    $existingOverride = Get-Content -Raw -LiteralPath $overridePath
    if ($existingOverride.StartsWith($generatedOverrideHeader)) {
      Remove-Item -LiteralPath $overridePath -Force
    }
  }

  if ($isWindowsHost -and -not (Test-Path $overridePath)) {
    $generatedOverride | Set-Content -Encoding UTF8 -NoNewline -LiteralPath $overridePath
    $createdOverride = $true
  }

  Push-Location $repoRoot
  try {
    & $flutterBin @FlutterArgs
    if ($null -ne $LASTEXITCODE) {
      $exitCode = $LASTEXITCODE
    }
  } finally {
    Pop-Location
  }
} finally {
  if ($createdOverride -and (Test-Path $overridePath)) {
    Remove-Item -LiteralPath $overridePath -Force
  }
}

exit $exitCode
